const CATEGORIES = {
  animales: {
    name: "[ESP] Animales",
    words: [
      { word: "León",       easyHint: "melena",      hardHint: "tarde" },
      { word: "Delfín",     easyHint: "olas",         hardHint: "sonrisa" },
      { word: "Águila",     easyHint: "viento",       hardHint: "moneda" },
      { word: "Elefante",   easyHint: "memoria",      hardHint: "gris" },
      { word: "Cocodrilo",  easyHint: "pantano",      hardHint: "bolso" },
      { word: "Jirafa",     easyHint: "ventana alta", hardHint: "manchas" },
      { word: "Pingüino",   easyHint: "hielo",        hardHint: "pajarita" },
      { word: "Tigre",      easyHint: "rayas",        hardHint: "naranja" },
      { word: "Oso Polar",  easyHint: "blanco",       hardHint: "quietud" },
      { word: "Camaleón",   easyHint: "máscara",      hardHint: "rama" },
      { word: "Gorila",     easyHint: "puño",         hardHint: "selva" },
      { word: "Canguro",    easyHint: "salto",        hardHint: "bolsillo" },
      { word: "Lobo",       easyHint: "aullido",      hardHint: "luna" },
      { word: "Pulpo",      easyHint: "tinta",        hardHint: "abrazo" },
      { word: "Murciélago", easyHint: "noche",        hardHint: "cueva" },
    ],
  },

  comidas: {
    name: "[ESP] Comidas y Bebidas",
    words: [
      { word: "Pizza",       easyHint: "triángulo",   hardHint: "Nápoles" },
      { word: "Sushi",       easyHint: "alga",        hardHint: "cuchillo" },
      { word: "Tacos",       easyHint: "doblez",      hardHint: "martes" },
      { word: "Paella",      easyHint: "amarillo",    hardHint: "domingo" },
      { word: "Hamburguesa", easyHint: "redondo",     hardHint: "Nueva York" },
      { word: "Chocolate",   easyHint: "cacao",       hardHint: "amargura" },
      { word: "Helado",      easyHint: "cono",        hardHint: "verano" },
      { word: "Café",        easyHint: "amargo",      hardHint: "madrugada" },
      { word: "Limonada",    easyHint: "amarillo",    hardHint: "sed" },
      { word: "Croissant",   easyHint: "luna",        hardHint: "mantequilla" },
      { word: "Ramen",       easyHint: "fideos",      hardHint: "lluvia" },
      { word: "Guacamole",   easyHint: "verde",       hardHint: "piedra" },
      { word: "Churros",     easyHint: "aceite",      hardHint: "feria" },
      { word: "Macarrones",  easyHint: "tubos",       hardHint: "codo" },
      { word: "Ceviche",     easyHint: "limón",       hardHint: "costa" },
    ],
  },

  deportes: {
    name: "[ESP] Deportes",
    words: [
      { word: "Fútbol",      easyHint: "césped",      hardHint: "domingo" },
      { word: "Baloncesto",  easyHint: "aro",         hardHint: "bote" },
      { word: "Tenis",       easyHint: "red",         hardHint: "pelota amarilla" },
      { word: "Natación",    easyHint: "cloro",       hardHint: "carril" },
      { word: "Ciclismo",    easyHint: "cadena",      hardHint: "montaña" },
      { word: "Boxeo",       easyHint: "guante",      hardHint: "campana" },
      { word: "Golf",        easyHint: "hoyo",        hardHint: "silencio" },
      { word: "Rugby",       easyHint: "óvalo",       hardHint: "barro" },
      { word: "Voleibol",    easyHint: "red",         hardHint: "playa" },
      { word: "Ajedrez",     easyHint: "torre",       hardHint: "silencio" },
      { word: "Esquí",       easyHint: "nieve",       hardHint: "velocidad" },
      { word: "Surf",        easyHint: "tabla",       hardHint: "sal" },
      { word: "Esgrima",     easyHint: "máscara",     hardHint: "línea" },
      { word: "Atletismo",   easyHint: "pista",       hardHint: "cronómetro" },
      { word: "Béisbol",     easyHint: "bate",        hardHint: "diamante" },
    ],
  },

  peliculas: {
    name: "[ESP] Películas Famosas",
    words: [
      { word: "Titanic",      easyHint: "hielo",        hardHint: "puerta" },
      { word: "El Padrino",   easyHint: "oferta",       hardHint: "gato" },
      { word: "Avengers",     easyHint: "escudo",       hardHint: "guantelete" },
      { word: "Matrix",       easyHint: "pastilla",     hardHint: "cuchara" },
      { word: "Joker",        easyHint: "pintura",      hardHint: "escalera" },
      { word: "Interstellar", easyHint: "agujero",      hardHint: "reloj" },
      { word: "El Rey León",  easyHint: "roca",         hardHint: "sombra" },
      { word: "Harry Potter", easyHint: "escoba",       hardHint: "cicatriz" },
      { word: "Inception",    easyHint: "trompo",       hardHint: "arquitecto" },
      { word: "Forrest Gump", easyHint: "correr",       hardHint: "pluma" },
      { word: "Shrek",        easyHint: "cebolla",      hardHint: "pantano" },
      { word: "Gladiador",    easyHint: "arena",        hardHint: "guante" },
      { word: "Coco",         easyHint: "calavera",     hardHint: "marigold" },
      { word: "Star Wars",    easyHint: "sable",        hardHint: "fuerza" },
      { word: "Alien",        easyHint: "huevo",        hardHint: "tubo" },
    ],
  },

  profesiones: {
    name: "[ESP] Profesiones",
    words: [
      { word: "Cirujano",      easyHint: "bisturí",      hardHint: "guantes" },
      { word: "Astronauta",    easyHint: "vacío",        hardHint: "flotación" },
      { word: "Bombero",       easyHint: "escalera",     hardHint: "rojo" },
      { word: "Arqueólogo",    easyHint: "pincel",       hardHint: "polvo" },
      { word: "Piloto",        easyHint: "altitud",      hardHint: "nubes" },
      { word: "Chef",          easyHint: "cuchillo",     hardHint: "sombrero" },
      { word: "Fotógrafo",     easyHint: "objetivo",     hardHint: "instante" },
      { word: "Veterinario",   easyHint: "pata",         hardHint: "termómetro" },
      { word: "Juez",          easyHint: "martillo",     hardHint: "toga" },
      { word: "Detective",     easyHint: "lupa",         hardHint: "gabardina" },
      { word: "Arquitecto",    easyHint: "plano",        hardHint: "escuadra" },
      { word: "Buzo",          easyHint: "profundidad",  hardHint: "burbuja" },
      { word: "Mago",          easyHint: "ilusión",      hardHint: "sombrero" },
      { word: "Sommelier",     easyHint: "corcho",       hardHint: "nariz" },
      { word: "Taxidermista",  easyHint: "relleno",      hardHint: "aguja" },
    ],
  },

  paises: {
    name: "[ESP] Países del Mundo",
    words: [
      { word: "Brasil",     easyHint: "samba",       hardHint: "verde" },
      { word: "Japón",      easyHint: "cerezo",      hardHint: "papel" },
      { word: "Egipto",     easyHint: "arena",       hardHint: "vendas" },
      { word: "Australia",  easyHint: "bolsa",       hardHint: "upside down" },
      { word: "Rusia",      easyHint: "frío",        hardHint: "muñeca" },
      { word: "México",     easyHint: "picante",     hardHint: "cactus" },
      { word: "India",      easyHint: "especias",    hardHint: "elefante" },
      { word: "Noruega",    easyHint: "aurora",      hardHint: "fiordo" },
      { word: "Marruecos",  easyHint: "mosaico",     hardHint: "alfombra" },
      { word: "Grecia",     easyHint: "columna",     hardHint: "oliva" },
      { word: "Argentina",  easyHint: "tango",       hardHint: "pampa" },
      { word: "Islandia",   easyHint: "volcán",      hardHint: "vapor" },
      { word: "China",      easyHint: "muralla",     hardHint: "dragón" },
      { word: "Kenya",      easyHint: "sabana",      hardHint: "maratón" },
      { word: "Perú",       easyHint: "niebla",      hardHint: "cóndor" },
    ],
  },

  lugares_esp: {
    name: "[ESP] Lugares Turísticos",
    words: [
      { word: "La Sagrada Familia",      easyHint: "agujas",      hardHint: "inacabado" },
      { word: "La Alhambra",             easyHint: "agua",        hardHint: "rojo" },
      { word: "El Coliseo",              easyHint: "arena",       hardHint: "ovación" },
      { word: "La Torre Eiffel",         easyHint: "hierro",      hardHint: "picnic" },
      { word: "Machu Picchu",            easyHint: "niebla",      hardHint: "perdido" },
      { word: "El Big Ben",              easyHint: "campana",     hardHint: "lluvia" },
      { word: "La Estatua de la Libertad", easyHint: "antorcha",  hardHint: "verde" },
      { word: "La Gran Muralla China",   easyHint: "dragones",    hardHint: "ladrillo" },
      { word: "El Taj Mahal",            easyHint: "mármol",      hardHint: "amor" },
      { word: "Las Pirámides de Giza",   easyHint: "triángulo",   hardHint: "esfinge" },
      { word: "El Partenón",             easyHint: "columna",     hardHint: "diosa" },
      { word: "La Fontana di Trevi",     easyHint: "moneda",      hardHint: "deseo" },
      { word: "El Angkor Wat",           easyHint: "selva",       hardHint: "amanecer" },
      { word: "El Cristo Redentor",      easyHint: "brazos",      hardHint: "cima" },
      { word: "La Capilla Sixtina",      easyHint: "techo",       hardHint: "dedo" },
    ],
  },

  landmarks: {
    name: "[ENG] Famous Landmarks",
    words: [
      { word: "Stonehenge",             easyHint: "circle",      hardHint: "solstice" },
      { word: "Niagara Falls",          easyHint: "roar",        hardHint: "barrel" },
      { word: "Mount Everest",          easyHint: "oxygen",      hardHint: "flag" },
      { word: "Amazon Rainforest",      easyHint: "humid",       hardHint: "jaguar" },
      { word: "Golden Gate Bridge",     easyHint: "fog",         hardHint: "orange" },
      { word: "Grand Canyon",           easyHint: "layers",      hardHint: "mule" },
      { word: "Burj Khalifa",           easyHint: "elevator",    hardHint: "desert" },
      { word: "Sydney Opera House",     easyHint: "sails",       hardHint: "harbor" },
      { word: "Machu Picchu",           easyHint: "clouds",      hardHint: "llama" },
      { word: "Petra",                  easyHint: "carved",      hardHint: "rose" },
      { word: "Chichen Itza",           easyHint: "shadow",      hardHint: "snake" },
      { word: "Vatican City",           easyHint: "dome",        hardHint: "smoke" },
      { word: "Mount Fuji",             easyHint: "snow cap",    hardHint: "tea" },
      { word: "Santorini",              easyHint: "blue",        hardHint: "caldera" },
      { word: "Yellowstone",            easyHint: "steam",       hardHint: "bison" },
    ],
  },

  animals_eng: {
    name: "[ENG] Animals",
    words: [
      { word: "Platypus",      easyHint: "bill",        hardHint: "paradox" },
      { word: "Cheetah",       easyHint: "spots",       hardHint: "blur" },
      { word: "Octopus",       easyHint: "ink",         hardHint: "jar" },
      { word: "Flamingo",      easyHint: "pink",        hardHint: "balance" },
      { word: "Komodo Dragon", easyHint: "tongue",      hardHint: "island" },
      { word: "Narwhal",       easyHint: "spiral",      hardHint: "myth" },
      { word: "Snow Leopard",  easyHint: "invisible",   hardHint: "altitude" },
      { word: "Axolotl",       easyHint: "regrow",      hardHint: "smile" },
      { word: "Pangolin",      easyHint: "scales",      hardHint: "roll" },
      { word: "Blue Whale",    easyHint: "deep",        hardHint: "song" },
      { word: "Peacock",       easyHint: "fan",         hardHint: "eyes" },
      { word: "Tarantula",     easyHint: "silk",        hardHint: "velvet" },
      { word: "Manta Ray",     easyHint: "glide",       hardHint: "cape" },
      { word: "Panda",         easyHint: "bamboo",      hardHint: "mask" },
      { word: "Chameleon",     easyHint: "branch",      hardHint: "mood" },
    ],
  },

  foods_eng: {
    name: "[ENG] Foods & Drinks",
    words: [
      { word: "Croissant",   easyHint: "layers",      hardHint: "Monday" },
      { word: "Burritos",    easyHint: "wrap",        hardHint: "blanket" },
      { word: "Dim Sum",     easyHint: "basket",      hardHint: "Sunday" },
      { word: "Tiramisu",    easyHint: "espresso",    hardHint: "cloud" },
      { word: "Pad Thai",    easyHint: "wok",         hardHint: "peanut" },
      { word: "Hummus",      easyHint: "dip",         hardHint: "stone" },
      { word: "Kimchi",      easyHint: "jar",         hardHint: "winter" },
      { word: "Pretzels",    easyHint: "twist",       hardHint: "knot" },
      { word: "Pho",         easyHint: "broth",       hardHint: "dawn" },
      { word: "Gelato",      easyHint: "scoop",       hardHint: "cobblestone" },
      { word: "Baklava",     easyHint: "honey",       hardHint: "scroll" },
      { word: "Matcha Latte",easyHint: "foam",        hardHint: "ceremony" },
      { word: "Empanadas",   easyHint: "pocket",      hardHint: "half moon" },
      { word: "Waffles",     easyHint: "grid",        hardHint: "Sunday" },
      { word: "Miso Soup",   easyHint: "paste",       hardHint: "morning" },
    ],
  },
};
